// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5i46hE8inlB0bVUPIO2XdtmPJlzp_jy4',
    appId: '1:759896925593:web:ea4a853a6f71820dd45f08',
    messagingSenderId: '759896925593',
    projectId: 'dimappointfy',
    authDomain: 'dimappointfy.firebaseapp.com',
    storageBucket: 'dimappointfy.appspot.com',
    measurementId: 'G-X66VH3R8DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Xwgw-9T1kws5URCwQJvWwzC29Sj74O4',
    appId: '1:759896925593:android:a76fee1310741f59d45f08',
    messagingSenderId: '759896925593',
    projectId: 'dimappointfy',
    storageBucket: 'dimappointfy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdaOFNM9mst1KrbUYGkBwZDVl0GOjRShc',
    appId: '1:759896925593:ios:b90b0bd11f78c504d45f08',
    messagingSenderId: '759896925593',
    projectId: 'dimappointfy',
    storageBucket: 'dimappointfy.appspot.com',
    iosClientId: '759896925593-q33ek3lec7a4nqbvhurn6p89v3ieqbon.apps.googleusercontent.com',
    iosBundleId: 'com.dimappointfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdaOFNM9mst1KrbUYGkBwZDVl0GOjRShc',
    appId: '1:759896925593:ios:9d51719b080cf0eed45f08',
    messagingSenderId: '759896925593',
    projectId: 'dimappointfy',
    storageBucket: 'dimappointfy.appspot.com',
    iosClientId: '759896925593-v9evbknjb07ortj3if7mj7dkh71ctjq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
